name: AutoMerge
on:
  pull_request:
    types: [labeled]
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: AutoMerge
        uses: devmasx/merge-branch@v1.1.0
        with:
          label_name: 'automerge'
          target_branch: 'translations_delivery'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}