name: AutoMerge
on:
  pull_request:
    types: [labeled]
    branches:
      - translations_delivery
jobs:
  Run Actions:
    runs-on: [ubuntu-latest]
    steps:
    - name: Automatically Merge PR
      uses: plm9606/automerge_actions@1.0.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}