name: automerge
on:
  pull_request:
    branches-ignore:
      - master
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "JamesMarkWilton/automerge_smartling_pr@master"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"